# Site settings
title: 云牙
#email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  如采自淤泥的藕，洗净了污浊，却洗不掉污斑
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://xieyunzi.github.io" # the base hostname & protocol for your site
github_username: xieyunzi

timezone: Asia/Shanghai

# Build settings
markdown: kramdown
kramdown:
  input: GFM
  toc_levels: 1..6
